packages:
  - "apps/*"
  - "packages/*"
  - "backend/*"
  - "backend/airtable-sync/shared"
  - "backend/airtable-sync/airtable-sync-pulumi"
  - "backend/airtable-sync/functions/*"
  - "backend/scripts/packaging"
