version: '3.8'

services:
  app:
    image: europe-west2-docker.pkg.dev/cozemble/main-docker-repo/breezbook/backend-airtable:latest
    env_file:
      - .env-docker-compose
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env-docker-compose
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  postgres_data:
