version: '3.8'

services:
  app:
    image: europe-west2-docker.pkg.dev/cozemble/main-docker-repo/breezbook/backend-airtable:latest
    environment:
      - PGHOST=db
      - PGUSER=user
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - PGPORT=5434
      - PG_ADMIN_USER=user
      - PG_ADMIN_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PGPORT=5434
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  postgres_data:
